services:
  app:
    platform: linux/amd64
    build:
      context: .
      dockerfile: Dockerfile
    container_name: effective-mobile-app
    env_file: .env
    depends_on:
      - db
      - migrate
    networks:
      - effective-mobile-network
    ports:
      - ${PORT}:${PORT}

  migrate:
    image: migrate/migrate
    networks:
      - effective-mobile-network
    container_name: effective-mobile-migrate
    volumes:
      - ./db/migrations:/migrations
    command: [ "-path", "/migrations", "-database",  "postgres://${POSTGRES_USER}:${POSTGRES_PASSWORD}@db:5432/${POSTGRES_DB}?sslmode=disable", "up" ]
    depends_on:
      db:
        condition: service_healthy

  db:
    image: postgres:latest
    container_name: effective-mobile-postgres
    env_file: .env
    ports:
      - "5432:5432"
    networks:
      - effective-mobile-network
    healthcheck:
      test: pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}
      interval: 10s
      timeout: 3s
      retries: 5


networks:
    effective-mobile-network:
        driver: bridge